/**
 * Compliance Export & Verify
 *
 * Exports a tamper-evident bundle of signed traces.
 * The bundle is a directory containing:
 *   bundle.json          — all signed traces + Merkle chain + audit reports
 *   reports/<sessionId>.md — human-readable report per session
 *   VERIFY.md            — instructions for independent verification
 */

import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import type { ComplianceBundle, VerificationResult } from './types.js';
import { loadOrCreateKeyPair, signTrace } from './sign.js';
import { buildChain, verifyChain } from './merkle.js';
import { generateAuditReport, formatAuditReportMarkdown } from './report.js';
import { loadCognitiveTrace } from '../cognitive/capture.js';
import { verifySignedTrace } from './sign.js';

const VERIFY_INSTRUCTIONS = `# How to Verify This Compliance Bundle

This bundle was generated by agentgram TraceVault.
Every trace is cryptographically signed and linked in a tamper-evident chain.

## Quick Verify

\`\`\`bash
npx agentgram verify --compliance --bundle <path-to-bundle>
\`\`\`

## Manual Verify (Auditor Instructions)

1. **Check signature** for each trace in \`bundle.json\`:
   - Compute SHA-256 of \`traceJson\`
   - Verify Ed25519 signature using \`publicKeyPem\` against the hash

2. **Check chain integrity**:
   - Start from chain[0] where \`previousNodeHash\` === GENESIS (all zeros)
   - For each node[i]: verify \`nodeHash\` = SHA-256(\`traceHash\` + \`previousNodeHash\` + \`chainIndex\`)
   - Verify \`previousNodeHash\` of node[i+1] === \`nodeHash\` of node[i]

3. **Cross-reference**:
   - Every \`signedTraces[i].chainIndex\` must equal \`merkleChain[i].index\`
   - \`bundleHash\` (if present) must match SHA-256 of bundle JSON without the \`bundleHash\` field

## What This Proves

- The trace content was not modified after signing (signature)
- No traces were deleted from the sequence (chain)
- Traces were produced in the recorded order (chain index)
- The signing key is identified by its SHA-256 fingerprint (keyId)

## Compliance Standards

This format satisfies:
- SOC 2 Type II: CC6.1 (logical access), CC7.2 (system incidents audit trail)
- HIPAA: §164.312(b) Audit controls
- ISO 27001: A.12.4 Logging and monitoring
`;

// ---------------------------------------------------------------------------
// Export compliance bundle
// ---------------------------------------------------------------------------

export interface ExportOptions {
  sessionIds: string[];
  outputDir: string;
  agentgramDir?: string;
  developer?: string;
  /** If true, overwrite existing bundle */
  force?: boolean;
}

export async function exportComplianceBundle(options: ExportOptions): Promise<{
  bundlePath: string;
  sessionCount: number;
  errors: string[];
}> {
  const {
    sessionIds,
    outputDir,
    agentgramDir = '.agentgram',
    developer,
    force = false,
  } = options;

  const errors: string[] = [];
  const bundlePath = path.resolve(outputDir);

  if (fs.existsSync(bundlePath) && !force) {
    throw new Error(`Output directory already exists: ${bundlePath}. Use --force to overwrite.`);
  }

  fs.mkdirSync(path.join(bundlePath, 'reports'), { recursive: true });

  const keyPair = loadOrCreateKeyPair();
  const signedTraces = [];
  let chainIndex = 0;
  let previousHash = '0'.repeat(64); // GENESIS

  for (const sessionId of sessionIds) {
    const trace = loadCognitiveTrace(sessionId, agentgramDir);
    if (!trace) {
      errors.push(`Session not found: ${sessionId}`);
      continue;
    }

    const signed = signTrace(trace, keyPair, previousHash, chainIndex);
    signedTraces.push(signed);
    previousHash = signed.traceHash;
    chainIndex++;
  }

  // Build Merkle chain
  const merkleChain = buildChain(signedTraces);
  const chainVerification = verifyChain(merkleChain, signedTraces);

  // Generate reports
  const reports = [];
  for (let i = 0; i < signedTraces.length; i++) {
    const signed = signedTraces[i]!;
    const trace = JSON.parse(signed.traceJson) as Parameters<typeof generateAuditReport>[0];
    const report = generateAuditReport(trace, signed, chainVerification.intact, developer);
    reports.push(report);

    // Write individual markdown report
    const md = formatAuditReportMarkdown(report);
    fs.writeFileSync(
      path.join(bundlePath, 'reports', `${report.sessionId}.md`),
      md,
    );
  }

  // Build bundle
  const bundle: ComplianceBundle = {
    version: '1',
    exportedAt: new Date().toISOString(),
    exportedBy: developer,
    signedTraces,
    merkleChain,
    reports,
  };

  // Compute bundle hash (integrity check for the whole export)
  const bundleForHash = JSON.stringify(bundle);
  bundle.bundleHash = createHash('sha256').update(bundleForHash).digest('hex');

  // Write files
  fs.writeFileSync(path.join(bundlePath, 'bundle.json'), JSON.stringify(bundle, null, 2));
  fs.writeFileSync(path.join(bundlePath, 'VERIFY.md'), VERIFY_INSTRUCTIONS);

  // Write summary README
  const summary = `# Compliance Bundle

**Exported:** ${bundle.exportedAt}
**Sessions:** ${signedTraces.length}
**Chain intact:** ${chainVerification.intact ? '✅' : '❌'}
**Key ID:** \`${keyPair.keyId}\`

## Sessions

${reports.map((r, i) => `${i + 1}. [\`${r.sessionId}\`](./reports/${r.sessionId}.md) — ${r.summary.slice(0, 80)}`).join('\n')}

## Verify

\`\`\`bash
npx agentgram verify --compliance --bundle .
\`\`\`

See [VERIFY.md](./VERIFY.md) for manual verification instructions.
`;
  fs.writeFileSync(path.join(bundlePath, 'README.md'), summary);

  return {
    bundlePath,
    sessionCount: signedTraces.length,
    errors,
  };
}

// ---------------------------------------------------------------------------
// Verify a compliance bundle
// ---------------------------------------------------------------------------

export function verifyComplianceBundle(bundleDir: string): VerificationResult[] {
  const bundlePath = path.join(bundleDir, 'bundle.json');

  if (!fs.existsSync(bundlePath)) {
    throw new Error(`No bundle.json found in ${bundleDir}`);
  }

  const bundle = JSON.parse(fs.readFileSync(bundlePath, 'utf8')) as ComplianceBundle;
  const results: VerificationResult[] = [];

  // Verify chain integrity first
  const chainVerification = verifyChain(bundle.merkleChain, bundle.signedTraces);

  for (let i = 0; i < bundle.signedTraces.length; i++) {
    const signed = bundle.signedTraces[i]!;
    const { signatureValid, hashMatch, errors } = verifySignedTrace(signed);

    let sessionId = `session-${i}`;
    try {
      const trace = JSON.parse(signed.traceJson) as { sessionId?: string };
      if (trace.sessionId) sessionId = trace.sessionId;
    } catch { /* ignore */ }

    results.push({
      valid: signatureValid && hashMatch && chainVerification.intact,
      sessionId,
      signatureValid,
      chainIntact: chainVerification.intact,
      hashMatch,
      errors: [
        ...errors,
        ...(chainVerification.firstBrokenIndex === i ? chainVerification.errors : []),
      ],
    });
  }

  return results;
}
