#!/usr/bin/env npx tsx
/**
 * Push curated recipes to GitHub registry.
 *
 * Reads from registry/ (generated by curate.ts) and uploads each recipe
 * as a SharedRecipe to eclaireai/agentgram-recipes, replacing old content.
 *
 * Usage:
 *   GITHUB_TOKEN=xxx npx tsx seeds/push-to-registry.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';

const OWNER = 'eclaireai';
const REPO = 'agentgram-recipes';
const BRANCH = 'main';
const REGISTRY_DIR = path.resolve('registry');
const TOKEN = process.env.GITHUB_TOKEN;

if (!TOKEN) {
  console.error('❌  GITHUB_TOKEN env var is required');
  process.exit(1);
}

const headers = {
  Authorization: `token ${TOKEN}`,
  Accept: 'application/vnd.github.v3+json',
  'Content-Type': 'application/json',
  'User-Agent': 'agentgram-seed/1.0',
};

// ---------------------------------------------------------------------------
// GitHub API helpers
// ---------------------------------------------------------------------------

async function getFileSha(filePath: string): Promise<string | null> {
  const res = await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${filePath}?ref=${BRANCH}`, { headers });
  if (res.status === 404) return null;
  const data = await res.json() as { sha: string };
  return data.sha ?? null;
}

async function putFile(filePath: string, content: string, message: string, sha?: string | null): Promise<void> {
  const body: Record<string, unknown> = {
    message,
    content: Buffer.from(content).toString('base64'),
    branch: BRANCH,
  };
  if (sha) body.sha = sha;

  const res = await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${filePath}`, {
    method: 'PUT',
    headers,
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Failed to PUT ${filePath}: ${res.status} ${err}`);
  }
}

async function deleteFile(filePath: string, message: string): Promise<void> {
  const sha = await getFileSha(filePath);
  if (!sha) return;

  const res = await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${filePath}`, {
    method: 'DELETE',
    headers,
    body: JSON.stringify({ message, sha, branch: BRANCH }),
  });

  if (!res.ok && res.status !== 404) {
    const err = await res.text();
    throw new Error(`Failed to DELETE ${filePath}: ${res.status} ${err}`);
  }
}

async function listDirContents(dirPath: string): Promise<string[]> {
  const res = await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${dirPath}?ref=${BRANCH}`, { headers });
  if (res.status === 404) return [];
  const data = await res.json() as Array<{ name: string; type: string; path: string }>;
  if (!Array.isArray(data)) return [];

  const files: string[] = [];
  for (const item of data) {
    if (item.type === 'file') {
      files.push(item.path);
    } else if (item.type === 'dir') {
      const nested = await listDirContents(item.path);
      files.push(...nested);
    }
  }
  return files;
}

// ---------------------------------------------------------------------------
// Recipe conversion
// ---------------------------------------------------------------------------

interface LocalRecipe {
  name: string;
  description: string;
  sourceSessionId: string;
  steps: Array<{ action: string; target: string; description: string; pattern?: string; expect?: string }>;
  parameters: Record<string, string>;
  tags: string[];
  stack: string[];
}

interface SharedRecipe extends LocalRecipe {
  metadata: {
    id: string;
    author: string;
    createdAt: string;
    updatedAt: string;
    downloads: number;
    rating: number;
    ratingCount: number;
    sourceAgent: string;
    checksum: string;
  };
}

function toShared(recipe: LocalRecipe, id: string, category: string): SharedRecipe {
  const json = JSON.stringify(recipe);
  const checksum = createHash('sha256').update(json).digest('hex').slice(0, 16);
  return {
    ...recipe,
    metadata: {
      id,
      author: 'agentgram-team',
      createdAt: '2026-03-27T00:00:00Z',
      updatedAt: new Date().toISOString(),
      downloads: 0,
      rating: 0,
      ratingCount: 0,
      sourceAgent: 'curator',
      checksum,
    },
  };
}

interface IndexEntry {
  id: string;
  name: string;
  description: string;
  author: string;
  tags: string[];
  sourceAgent: string;
  downloads: number;
  rating: number;
  createdAt: string;
  stepCount: number;
  category: string;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log('🚀  Pushing curated recipes to eclaireai/agentgram-recipes\n');

  // 1. Collect all local recipes
  const categories = fs.readdirSync(REGISTRY_DIR).filter((f) => {
    return fs.statSync(path.join(REGISTRY_DIR, f)).isDirectory();
  });

  const allRecipes: Array<{ id: string; category: string; shared: SharedRecipe }> = [];

  for (const category of categories) {
    const catDir = path.join(REGISTRY_DIR, category);
    const slugs = fs.readdirSync(catDir).filter((f) => fs.statSync(path.join(catDir, f)).isDirectory());

    for (const slug of slugs) {
      const recipePath = path.join(catDir, slug, 'recipe.json');
      if (!fs.existsSync(recipePath)) continue;

      const recipe = JSON.parse(fs.readFileSync(recipePath, 'utf8')) as LocalRecipe;
      const id = slug;
      const shared = toShared(recipe, id, category);
      allRecipes.push({ id, category, shared });
    }
  }

  console.log(`📦  Found ${allRecipes.length} curated recipes in registry/\n`);

  // 2. Delete old recipe files
  console.log('🗑   Clearing old recipes from registry...');
  const existing = await listDirContents('recipes');
  console.log(`    ${existing.length} old files to remove`);

  for (const file of existing) {
    process.stdout.write(`    - ${file}\r`);
    await deleteFile(file, 'chore: clear old mined recipes');
    await new Promise((r) => setTimeout(r, 200)); // rate limit
  }
  console.log(`    ✔  Cleared ${existing.length} old files\n`);

  // 3. Upload new recipes
  console.log('⬆️   Uploading new recipes...');
  const indexEntries: IndexEntry[] = [];

  for (const { id, category, shared } of allRecipes) {
    const filePath = `recipes/${category}/${id}.json`;
    const content = JSON.stringify(shared, null, 2);
    process.stdout.write(`    → ${filePath}\r`);
    await putFile(filePath, content, `feat: add curated recipe ${id}`);
    await new Promise((r) => setTimeout(r, 300)); // rate limit

    indexEntries.push({
      id,
      name: shared.name,
      description: shared.description,
      author: shared.metadata.author,
      tags: shared.tags,
      sourceAgent: shared.metadata.sourceAgent,
      downloads: 0,
      rating: 0,
      createdAt: shared.metadata.createdAt,
      stepCount: shared.steps.length,
      category,
    });
  }
  console.log(`\n    ✔  Uploaded ${allRecipes.length} recipes\n`);

  // 4. Update index.json
  console.log('📑  Updating index.json...');
  const index = {
    version: '2',
    updatedAt: new Date().toISOString(),
    totalRecipes: indexEntries.length,
    recipes: indexEntries.sort((a, b) => a.name.localeCompare(b.name)),
  };

  const indexSha = await getFileSha('index.json');
  await putFile('index.json', JSON.stringify(index, null, 2), 'chore: update index — 39 curated recipes', indexSha);
  console.log('    ✔  index.json updated\n');

  // 5. Summary
  console.log('✅  Done!\n');
  console.log(`  Recipes: ${allRecipes.length}`);
  console.log(`  Repo:    https://github.com/${OWNER}/${REPO}`);
  console.log(`  Index:   https://raw.githubusercontent.com/${OWNER}/${REPO}/main/index.json`);

  const byCategory: Record<string, number> = {};
  for (const { category } of allRecipes) {
    byCategory[category] = (byCategory[category] ?? 0) + 1;
  }
  console.log('\n  By category:');
  for (const [cat, count] of Object.entries(byCategory)) {
    console.log(`    ${cat.padEnd(12)} ${count} recipes`);
  }
}

main().catch((err) => {
  console.error('❌', err.message);
  process.exit(1);
});
